# Generated by Django 5.1.7 on 2025-03-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.CharField(max_length=50),
        ),
    ]
