# Generated by Django 5.1.7 on 2025-03-12 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_news_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
