# Generated by Django 5.1.7 on 2025-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_news_likes_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, to='api.news'),
        ),
    ]
