# Generated by Django 5.1.7 on 2025-03-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.BigIntegerField(default=0),
        ),
    ]
